// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appTotalsForRange = `-- name: AppTotalsForRange :many
SELECT
    d.app_id,
    a.name AS app_name,
    a.bundle_id AS app_bundle_id,
    sum(d.total_s)::bigint AS total_s
FROM daily_app_totals d
LEFT JOIN apps a ON a.id = d.app_id
WHERE d.user_id = $1 AND d.day >= $2::timestamptz AND d.day < $3::timestamptz
GROUP BY d.app_id, a.name, a.bundle_id
`

type AppTotalsForRangeParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	FromDay pgtype.Timestamptz `json:"from_day"`
	ToDay   pgtype.Timestamptz `json:"to_day"`
}

type AppTotalsForRangeRow struct {
	AppID       pgtype.UUID `json:"app_id"`
	AppName     *string     `json:"app_name"`
	AppBundleID *string     `json:"app_bundle_id"`
	TotalS      int64       `json:"total_s"`
}

// Closed-period fast path for reports/apps: sums the daily_app_totals
// continuous aggregate over [from_day, to_day) per
// documentation/architecture-backend.md §Aggregation Strategy. Only used
// when the request has no device_id/precision filter — see
// internal/reports/service.go.
func (q *Queries) AppTotalsForRange(ctx context.Context, arg AppTotalsForRangeParams) ([]AppTotalsForRangeRow, error) {
	rows, err := q.db.Query(ctx, appTotalsForRange, arg.UserID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppTotalsForRangeRow
	for rows.Next() {
		var i AppTotalsForRangeRow
		if err := rows.Scan(
			&i.AppID,
			&i.AppName,
			&i.AppBundleID,
			&i.TotalS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryTotalsForRange = `-- name: CategoryTotalsForRange :many
SELECT
    d.category_id,
    c.name AS category_name,
    sum(d.total_s)::bigint AS total_s
FROM daily_category_totals d
LEFT JOIN categories c ON c.id = d.category_id
WHERE d.user_id = $1 AND d.day >= $2::timestamptz AND d.day < $3::timestamptz
GROUP BY d.category_id, c.name
`

type CategoryTotalsForRangeParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	FromDay pgtype.Timestamptz `json:"from_day"`
	ToDay   pgtype.Timestamptz `json:"to_day"`
}

type CategoryTotalsForRangeRow struct {
	CategoryID   pgtype.UUID `json:"category_id"`
	CategoryName *string     `json:"category_name"`
	TotalS       int64       `json:"total_s"`
}

// Closed-period fast path for reports/daily, reports/categories, and
// reports/summary's category breakdown: sums the daily_category_totals
// continuous aggregate over [from_day, to_day) per
// documentation/architecture-backend.md §Aggregation Strategy. Only used
// when the request has no device_id/precision filter (the aggregate has
// neither dimension) — see internal/reports/service.go.
func (q *Queries) CategoryTotalsForRange(ctx context.Context, arg CategoryTotalsForRangeParams) ([]CategoryTotalsForRangeRow, error) {
	rows, err := q.db.Query(ctx, categoryTotalsForRange, arg.UserID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryTotalsForRangeRow
	for rows.Next() {
		var i CategoryTotalsForRangeRow
		if err := rows.Scan(&i.CategoryID, &i.CategoryName, &i.TotalS); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityEventsForUser = `-- name: ListActivityEventsForUser :many
SELECT event_id, user_id, device_id, started_at, ended_at, duration_s, type, source, precision, app_id, raw_bundle_id, window_title, url, category_id, project_id, deleted, inserted_at, server_seq FROM activity_events
WHERE user_id = $1
  AND deleted = false
  AND started_at >= $2 AND started_at < $3
  AND ($4::uuid IS NULL OR app_id = $4)
  AND ($5::uuid IS NULL OR category_id = $5)
  AND ($6::uuid IS NULL OR project_id = $6)
  AND ($7::uuid IS NULL OR device_id = $7)
  AND ($8::text IS NULL OR precision = $8)
  AND (started_at, event_id) > ($9::timestamptz, $10::uuid)
ORDER BY started_at ASC, event_id ASC
LIMIT $11
`

type ListActivityEventsForUserParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	FromTs          pgtype.Timestamptz `json:"from_ts"`
	ToTs            pgtype.Timestamptz `json:"to_ts"`
	AppID           pgtype.UUID        `json:"app_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	DeviceID        pgtype.UUID        `json:"device_id"`
	Precision       *string            `json:"precision"`
	CursorStartedAt pgtype.Timestamptz `json:"cursor_started_at"`
	CursorEventID   pgtype.UUID        `json:"cursor_event_id"`
	PageLimit       int32              `json:"page_limit"`
}

// GET /v1/activities per documentation/api-reference.md §Activities &
// reports: raw tracked events for the authenticated user, filterable by
// time range, app, category, project, device, and precision. Scoped by
// user_id per documentation/security.md §Tenant Isolation. Soft-deleted
// (deleted = true) rows are excluded, matching the CRUD groups' convention
// of excluding tombstoned rows from a "current state" list.
//
// Keyset-paginated on (started_at, event_id) ascending rather than the
// server_seq cursor other CRUD lists use: an activity-events list is
// naturally consumed in chronological order over an explicit time range,
// and started_at is the hypertable's own partitioning column, so ordering
// on it lets Postgres use the activity_events_user_started_idx index
// instead of the server_seq index. The initial page passes
// cursor_started_at = '-infinity' and cursor_event_id =
// '00000000-0000-0000-0000-000000000000' (see internal/activities'
// cursor.go), which sorts before every real row.
//
// sqlc.narg filters: a NULL argument (an omitted query-string filter)
// disables that filter's predicate entirely via the "IS NULL OR" branch.
func (q *Queries) ListActivityEventsForUser(ctx context.Context, arg ListActivityEventsForUserParams) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, listActivityEventsForUser,
		arg.UserID,
		arg.FromTs,
		arg.ToTs,
		arg.AppID,
		arg.CategoryID,
		arg.ProjectID,
		arg.DeviceID,
		arg.Precision,
		arg.CursorStartedAt,
		arg.CursorEventID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvent
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.DeviceID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationS,
			&i.Type,
			&i.Source,
			&i.Precision,
			&i.AppID,
			&i.RawBundleID,
			&i.WindowTitle,
			&i.Url,
			&i.CategoryID,
			&i.ProjectID,
			&i.Deleted,
			&i.InsertedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rawActivityEventsForReport = `-- name: RawActivityEventsForReport :many
SELECT
    e.device_id,
    e.app_id,
    a.name AS app_name,
    a.bundle_id AS app_bundle_id,
    e.category_id,
    c.name AS category_name,
    e.project_id,
    p.name AS project_name,
    e.started_at,
    e.ended_at
FROM activity_events e
LEFT JOIN apps a ON a.id = e.app_id
LEFT JOIN categories c ON c.id = e.category_id
LEFT JOIN projects p ON p.id = e.project_id
WHERE e.user_id = $1
  AND e.deleted = false
  AND e.started_at < $2 AND e.ended_at > $3
  AND ($4::uuid IS NULL OR e.app_id = $4)
  AND ($5::uuid IS NULL OR e.category_id = $5)
  AND ($6::uuid IS NULL OR e.project_id = $6)
  AND ($7::uuid IS NULL OR e.device_id = $7)
  AND ($8::text IS NULL OR e.precision = $8)
ORDER BY e.device_id, e.started_at
`

type RawActivityEventsForReportParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
	FromTs     pgtype.Timestamptz `json:"from_ts"`
	AppID      pgtype.UUID        `json:"app_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	Precision  *string            `json:"precision"`
}

type RawActivityEventsForReportRow struct {
	DeviceID     pgtype.UUID        `json:"device_id"`
	AppID        pgtype.UUID        `json:"app_id"`
	AppName      *string            `json:"app_name"`
	AppBundleID  *string            `json:"app_bundle_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CategoryName *string            `json:"category_name"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ProjectName  *string            `json:"project_name"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
}

// The report layer's raw-event pass, per documentation/architecture-backend.md
// §Aggregation Strategy: used (a) always for the current/partial period,
// and (b) as the only path for filters (device_id, precision) or
// dimensions (project) the continuous aggregates cannot serve, since
// daily_app_totals/daily_category_totals carry no device_id or precision
// column and no project-dimensioned aggregate exists at all — see
// internal/reports' service.go doc comment for the full resolution.
//
// Selects events overlapping [from_ts, to_ts) — not merely started within
// it — so an event that begins before the window and ends inside it (or
// vice versa) is still included for trimming, which clips each event to
// the window before merging. Joins apps/categories/projects so the report
// layer never needs a second round trip to resolve display names.
func (q *Queries) RawActivityEventsForReport(ctx context.Context, arg RawActivityEventsForReportParams) ([]RawActivityEventsForReportRow, error) {
	rows, err := q.db.Query(ctx, rawActivityEventsForReport,
		arg.UserID,
		arg.ToTs,
		arg.FromTs,
		arg.AppID,
		arg.CategoryID,
		arg.ProjectID,
		arg.DeviceID,
		arg.Precision,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawActivityEventsForReportRow
	for rows.Next() {
		var i RawActivityEventsForReportRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.AppID,
			&i.AppName,
			&i.AppBundleID,
			&i.CategoryID,
			&i.CategoryName,
			&i.ProjectID,
			&i.ProjectName,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
