// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategoryForUser = `-- name: CreateCategoryForUser :one
INSERT INTO categories (
    id, user_id, name, color, productivity, created_at, updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, now(), now()
)
RETURNING id, user_id, name, color, productivity, created_at, updated_at, deleted_at, server_seq
`

type CreateCategoryForUserParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Name         string      `json:"name"`
	Color        string      `json:"color"`
	Productivity int16       `json:"productivity"`
}

// POST /v1/categories always creates a user-owned category (user_id set to
// the authenticated caller); a client cannot create a system default
// through this endpoint. id is server-generated (gen_random_uuid()): per
// documentation/database-schema.md's PK convention, categories are not in
// the client-supplied-UUIDv7 list (only activity_events, focus_sessions,
// projects, and tags are).
func (q *Queries) CreateCategoryForUser(ctx context.Context, arg CreateCategoryForUserParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategoryForUser,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Productivity,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Productivity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getCategoryForUser = `-- name: GetCategoryForUser :one
SELECT id, user_id, name, color, productivity, created_at, updated_at, deleted_at, server_seq FROM categories
WHERE id = $1 AND (user_id = $2 OR user_id IS NULL) AND deleted_at IS NULL
`

type GetCategoryForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// GET /v1/categories/{id}: readable if it's a system default or the
// caller's own, per database-schema.md's categories.user_id semantics.
func (q *Queries) GetCategoryForUser(ctx context.Context, arg GetCategoryForUserParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryForUser, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Productivity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getOwnCategoryForUser = `-- name: GetOwnCategoryForUser :one
SELECT id, user_id, name, color, productivity, created_at, updated_at, deleted_at, server_seq FROM categories
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetOwnCategoryForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Authorization check used before UPDATE/DELETE: unlike GetCategoryForUser,
// this only matches a category the caller owns (user_id = $2), never a
// system default (user_id IS NULL). System categories are read-only via
// the API — see internal/categories's service doc comment for why an
// attempt to PATCH/DELETE one is reported as 404 rather than 403, matching
// the cross-tenant 404-equivalence convention used elsewhere in this
// ticket.
func (q *Queries) GetOwnCategoryForUser(ctx context.Context, arg GetOwnCategoryForUserParams) (Category, error) {
	row := q.db.QueryRow(ctx, getOwnCategoryForUser, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Productivity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const listCategoriesForUser = `-- name: ListCategoriesForUser :many
SELECT id, user_id, name, color, productivity, created_at, updated_at, deleted_at, server_seq FROM categories
WHERE (user_id = $1 OR user_id IS NULL) AND deleted_at IS NULL AND server_seq > $2
ORDER BY server_seq ASC
LIMIT $3
`

type ListCategoriesForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

// GET /v1/categories per documentation/api-reference.md §CRUD groups.
// documentation/database-schema.md's categories table: "user_id IS NULL
// denotes a system default category available to every user; user_id set
// denotes a user's own custom category" — so the list a user sees is the
// union of every system default plus their own custom categories,
// keyset-paginated together by server_seq.
func (q *Queries) ListCategoriesForUser(ctx context.Context, arg ListCategoriesForUserParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Productivity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOwnCategoryForUser = `-- name: SoftDeleteOwnCategoryForUser :execrows
UPDATE categories
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteOwnCategoryForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// DELETE /v1/categories/{id}, restricted to categories the caller owns; a
// system default cannot be deleted through this query (zero rows if id
// resolves to one).
func (q *Queries) SoftDeleteOwnCategoryForUser(ctx context.Context, arg SoftDeleteOwnCategoryForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOwnCategoryForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOwnCategoryForUser = `-- name: UpdateOwnCategoryForUser :one
UPDATE categories
SET name = $3,
    color = $4,
    productivity = $5,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, color, productivity, created_at, updated_at, deleted_at, server_seq
`

type UpdateOwnCategoryForUserParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Name         string      `json:"name"`
	Color        string      `json:"color"`
	Productivity int16       `json:"productivity"`
}

// PATCH /v1/categories/{id}, restricted to categories the caller owns (see
// GetOwnCategoryForUser); a system default cannot be edited through this
// query (zero rows if id resolves to one).
func (q *Queries) UpdateOwnCategoryForUser(ctx context.Context, arg UpdateOwnCategoryForUserParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateOwnCategoryForUser,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Productivity,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Productivity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}
