// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    id, user_id, platform, name, model, os_version, app_version,
    last_seen_at, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6,
    now(), now()
)
RETURNING id, user_id, platform, name, model, os_version, app_version, last_seen_at, created_at, revoked_at
`

type CreateDeviceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Platform   string      `json:"platform"`
	Name       string      `json:"name"`
	Model      string      `json:"model"`
	OsVersion  string      `json:"os_version"`
	AppVersion string      `json:"app_version"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.Platform,
		arg.Name,
		arg.Model,
		arg.OsVersion,
		arg.AppVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, platform, name, model, os_version, app_version, last_seen_at, created_at, revoked_at FROM devices
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetDeviceByID(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, platform, name, model, os_version, app_version, last_seen_at, created_at, revoked_at FROM devices
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Name,
			&i.Model,
			&i.OsVersion,
			&i.AppVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE devices
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeDevice, id)
	return err
}

const touchDeviceLastSeen = `-- name: TouchDeviceLastSeen :exec
UPDATE devices
SET last_seen_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchDeviceLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchDeviceLastSeen, id)
	return err
}
