// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    id, user_id, platform, name, model, os_version, app_version,
    last_seen_at, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6,
    now(), now()
)
RETURNING id, user_id, platform, name, model, os_version, app_version, last_seen_at, created_at, revoked_at
`

type CreateDeviceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Platform   string      `json:"platform"`
	Name       string      `json:"name"`
	Model      string      `json:"model"`
	OsVersion  string      `json:"os_version"`
	AppVersion string      `json:"app_version"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.Platform,
		arg.Name,
		arg.Model,
		arg.OsVersion,
		arg.AppVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, platform, name, model, os_version, app_version, last_seen_at, created_at, revoked_at FROM devices
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type GetDeviceByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Scoped by user_id per documentation/security.md §Tenant Isolation: every
// query is scoped by user_id from the access token, so a request
// authenticated as one user can never read another user's device row.
func (q *Queries) GetDeviceByID(ctx context.Context, arg GetDeviceByIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, platform, name, model, os_version, app_version, last_seen_at, created_at, revoked_at FROM devices
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Name,
			&i.Model,
			&i.OsVersion,
			&i.AppVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE devices
SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeDeviceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Scoped by user_id per documentation/security.md §Tenant Isolation.
func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeDevice, arg.ID, arg.UserID)
	return err
}

const touchDeviceLastSeen = `-- name: TouchDeviceLastSeen :exec
UPDATE devices
SET last_seen_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type TouchDeviceLastSeenParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Scoped by user_id per documentation/security.md §Tenant Isolation.
func (q *Queries) TouchDeviceLastSeen(ctx context.Context, arg TouchDeviceLastSeenParams) error {
	_, err := q.db.Exec(ctx, touchDeviceLastSeen, arg.ID, arg.UserID)
	return err
}

const updateDeviceMetadata = `-- name: UpdateDeviceMetadata :one
UPDATE devices
SET name = $3,
    model = $4,
    os_version = $5,
    app_version = $6,
    last_seen_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, user_id, platform, name, model, os_version, app_version, last_seen_at, created_at, revoked_at
`

type UpdateDeviceMetadataParams struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Name       string      `json:"name"`
	Model      string      `json:"model"`
	OsVersion  string      `json:"os_version"`
	AppVersion string      `json:"app_version"`
}

// Scoped by user_id per documentation/security.md §Tenant Isolation. Used
// during login/refresh to refresh a previously-registered device's
// self-reported metadata and last_seen_at, per documentation/security.md
// §Token model ("a device row is created/updated and bound to the refresh
// token").
func (q *Queries) UpdateDeviceMetadata(ctx context.Context, arg UpdateDeviceMetadataParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceMetadata,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Model,
		arg.OsVersion,
		arg.AppVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateDeviceName = `-- name: UpdateDeviceName :one
UPDATE devices
SET name = $3
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, user_id, platform, name, model, os_version, app_version, last_seen_at, created_at, revoked_at
`

type UpdateDeviceNameParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

// Scoped by user_id per documentation/security.md §Tenant Isolation. Used by
// PATCH /v1/devices/{id} ("Rename a device" per documentation/api-reference.md
// §Devices).
func (q *Queries) UpdateDeviceName(ctx context.Context, arg UpdateDeviceNameParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceName, arg.ID, arg.UserID, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
