// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: focus_sessions.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFocusSessionForUser = `-- name: CreateFocusSessionForUser :one
INSERT INTO focus_sessions (
    id, user_id, device_id, project_id, kind, planned_duration_s,
    started_at, ended_at, status, note, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, now(), now()
)
RETURNING id, user_id, device_id, project_id, kind, planned_duration_s, started_at, ended_at, status, note, created_at, updated_at, deleted_at, server_seq
`

type CreateFocusSessionForUserParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Kind             string             `json:"kind"`
	PlannedDurationS *int32             `json:"planned_duration_s"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	Status           string             `json:"status"`
	Note             *string            `json:"note"`
}

// POST /v1/focus-sessions per documentation/api-reference.md §CRUD groups.
// id is caller-supplied (client-supplied-UUIDv7 entity per
// documentation/database-schema.md's PK convention, same as
// internal/sync's push-side UpsertFocusSession). device_id and project_id
// are validated by the caller (internal/focussessions's service) against
// the authenticated user before this INSERT runs, per
// documentation/security.md §Tenant Isolation — device_id is NOT NULL on
// this table (see documentation/database-schema.md's focus_sessions),
// so a caller must resolve a device it owns first.
func (q *Queries) CreateFocusSessionForUser(ctx context.Context, arg CreateFocusSessionForUserParams) (FocusSession, error) {
	row := q.db.QueryRow(ctx, createFocusSessionForUser,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.ProjectID,
		arg.Kind,
		arg.PlannedDurationS,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status,
		arg.Note,
	)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ProjectID,
		&i.Kind,
		&i.PlannedDurationS,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getFocusSessionForUser = `-- name: GetFocusSessionForUser :one
SELECT id, user_id, device_id, project_id, kind, planned_duration_s, started_at, ended_at, status, note, created_at, updated_at, deleted_at, server_seq FROM focus_sessions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetFocusSessionForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Tenant-scoped lookup for GET /v1/focus-sessions/{id} and as the
// authorization check before PATCH/DELETE. Zero rows for either "no such
// session" or "belongs to another user," reported identically as 404.
func (q *Queries) GetFocusSessionForUser(ctx context.Context, arg GetFocusSessionForUserParams) (FocusSession, error) {
	row := q.db.QueryRow(ctx, getFocusSessionForUser, arg.ID, arg.UserID)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ProjectID,
		&i.Kind,
		&i.PlannedDurationS,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const listFocusSessionsForUser = `-- name: ListFocusSessionsForUser :many
SELECT id, user_id, device_id, project_id, kind, planned_duration_s, started_at, ended_at, status, note, created_at, updated_at, deleted_at, server_seq FROM focus_sessions
WHERE user_id = $1 AND deleted_at IS NULL AND server_seq > $2
ORDER BY server_seq ASC
LIMIT $3
`

type ListFocusSessionsForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

// Keyset-paginated list for GET /v1/focus-sessions, per
// documentation/api-reference.md §Conventions. Scoped by user_id per
// documentation/security.md §Tenant Isolation; excludes soft-deleted rows.
func (q *Queries) ListFocusSessionsForUser(ctx context.Context, arg ListFocusSessionsForUserParams) ([]FocusSession, error) {
	rows, err := q.db.Query(ctx, listFocusSessionsForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FocusSession
	for rows.Next() {
		var i FocusSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.ProjectID,
			&i.Kind,
			&i.PlannedDurationS,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFocusSessionForUser = `-- name: SoftDeleteFocusSessionForUser :execrows
UPDATE focus_sessions
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteFocusSessionForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// DELETE /v1/focus-sessions/{id}. Soft delete via deleted_at so the
// deletion propagates as a tombstone through GET /v1/sync/changes.
func (q *Queries) SoftDeleteFocusSessionForUser(ctx context.Context, arg SoftDeleteFocusSessionForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFocusSessionForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFocusSessionForUser = `-- name: UpdateFocusSessionForUser :one
UPDATE focus_sessions
SET device_id = $3,
    project_id = $4,
    kind = $5,
    planned_duration_s = $6,
    started_at = $7,
    ended_at = $8,
    status = $9,
    note = $10,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, device_id, project_id, kind, planned_duration_s, started_at, ended_at, status, note, created_at, updated_at, deleted_at, server_seq
`

type UpdateFocusSessionForUserParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Kind             string             `json:"kind"`
	PlannedDurationS *int32             `json:"planned_duration_s"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	Status           string             `json:"status"`
	Note             *string            `json:"note"`
}

// PATCH /v1/focus-sessions/{id}. See queries/projects.sql's
// UpdateProjectForUser doc comment for the read-then-merge-then-write
// pattern and the updated_at rationale (server sets updated_at = now();
// this is a direct REST edit, not a push-path LWW write).
func (q *Queries) UpdateFocusSessionForUser(ctx context.Context, arg UpdateFocusSessionForUserParams) (FocusSession, error) {
	row := q.db.QueryRow(ctx, updateFocusSessionForUser,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.ProjectID,
		arg.Kind,
		arg.PlannedDurationS,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status,
		arg.Note,
	)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ProjectID,
		&i.Kind,
		&i.PlannedDurationS,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}
