// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	DeviceID    pgtype.UUID        `json:"device_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationS   *int32             `json:"duration_s"`
	Type        string             `json:"type"`
	Source      string             `json:"source"`
	Precision   string             `json:"precision"`
	AppID       pgtype.UUID        `json:"app_id"`
	RawBundleID *string            `json:"raw_bundle_id"`
	WindowTitle *string            `json:"window_title"`
	Url         *string            `json:"url"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Deleted     bool               `json:"deleted"`
	InsertedAt  pgtype.Timestamptz `json:"inserted_at"`
	ServerSeq   int64              `json:"server_seq"`
}

type App struct {
	ID                pgtype.UUID `json:"id"`
	BundleID          string      `json:"bundle_id"`
	Platform          string      `json:"platform"`
	Name              string      `json:"name"`
	DefaultCategoryID pgtype.UUID `json:"default_category_id"`
}

type Category struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	Color        string             `json:"color"`
	Productivity int16              `json:"productivity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq    int64              `json:"server_seq"`
}

type DailyAppTotal struct {
	UserID pgtype.UUID `json:"user_id"`
	Day    interface{} `json:"day"`
	AppID  pgtype.UUID `json:"app_id"`
	TotalS int64       `json:"total_s"`
}

type DailyCategoryTotal struct {
	UserID     pgtype.UUID `json:"user_id"`
	Day        interface{} `json:"day"`
	CategoryID pgtype.UUID `json:"category_id"`
	TotalS     int64       `json:"total_s"`
}

type DeletionRequest struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RequestedAt  pgtype.Timestamptz `json:"requested_at"`
	ExecuteAfter pgtype.Timestamptz `json:"execute_after"`
	ExecutedAt   pgtype.Timestamptz `json:"executed_at"`
}

type Device struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Platform   string             `json:"platform"`
	Name       string             `json:"name"`
	Model      string             `json:"model"`
	OsVersion  string             `json:"os_version"`
	AppVersion string             `json:"app_version"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type EventTag struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
}

type FocusSession struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Kind             string             `json:"kind"`
	PlannedDurationS *int32             `json:"planned_duration_s"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	Status           string             `json:"status"`
	Note             *string            `json:"note"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq        int64              `json:"server_seq"`
}

type HourlyCategoryTotal struct {
	UserID     pgtype.UUID `json:"user_id"`
	Hour       interface{} `json:"hour"`
	CategoryID pgtype.UUID `json:"category_id"`
	TotalS     int64       `json:"total_s"`
}

type Project struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	Color      string             `json:"color"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq  int64              `json:"server_seq"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	TokenHash  []byte             `json:"token_hash"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

type SessionTag struct {
	EntityID pgtype.UUID `json:"entity_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

type SyncCursor struct {
	DeviceID    pgtype.UUID        `json:"device_id"`
	LastPullSeq int64              `json:"last_pull_seq"`
	LastPushAt  pgtype.Timestamptz `json:"last_push_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq int64              `json:"server_seq"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	AppleUserID  *string            `json:"apple_user_id"`
	DisplayName  *string            `json:"display_name"`
	Role         string             `json:"role"`
	Timezone     *string            `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq    int64              `json:"server_seq"`
}

type UserAppSetting struct {
	UserID     pgtype.UUID        `json:"user_id"`
	AppID      pgtype.UUID        `json:"app_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	Excluded   bool               `json:"excluded"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ServerSeq  int64              `json:"server_seq"`
}
