// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActivityEventChangesForUser = `-- name: ListActivityEventChangesForUser :many
SELECT
    ae.event_id,
    ae.started_at,
    ae.ended_at,
    a.bundle_id AS app_bundle_id,
    c.name AS category_name,
    ae.precision,
    ae.deleted,
    ae.server_seq
FROM activity_events ae
LEFT JOIN apps a ON a.id = ae.app_id
LEFT JOIN categories c ON c.id = ae.category_id
WHERE ae.user_id = $1 AND ae.server_seq > $2 AND xid_before_snapshot_horizon(ae.xmin)
ORDER BY ae.server_seq ASC
LIMIT $3
`

type ListActivityEventChangesForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

type ListActivityEventChangesForUserRow struct {
	EventID      pgtype.UUID        `json:"event_id"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	AppBundleID  *string            `json:"app_bundle_id"`
	CategoryName *string            `json:"category_name"`
	Precision    string             `json:"precision"`
	Deleted      bool               `json:"deleted"`
	ServerSeq    int64              `json:"server_seq"`
}

// One page of GET /v1/sync/changes's "activity_events" entity, per
// documentation/sync-protocol.md §Pull. Scoped by user_id per
// documentation/security.md §Tenant Isolation; ordered by the global
// server_seq sequence (migration 000021/000022) for strict keyset
// pagination. $3 is the caller-requested page size PLUS ONE (see
// internal/sync's pull service), so the caller can detect "more rows
// exist beyond this page" without a second round trip. app_bundle_id and
// category_name are resolved via LEFT JOIN so a null app_id/category_id
// (never yet resolved) doesn't drop the row, matching
// documentation/sync-protocol.md's upsert shape
// ({"app_bundle_id": ..., "category": ...}).
//
// xid_before_snapshot_horizon(ae.xmin) (migration 000024) gates delivery
// on the pulling transaction's MVCC snapshot horizon rather than trusting
// server_seq alone: nextval()-assigned server_seq is not commit-ordered,
// so a row from an as-yet-uncommitted transaction can carry a LOWER
// server_seq than one this pull is about to deliver. Excluding any row
// whose xmin isn't safely before every in-flight transaction as of this
// pull's snapshot means next_cursor (computed in internal/sync/pull.go)
// never advances past a row that could still be uncommitted — see
// migration 000024's comment for the full invariant and the widening
// math. This query MUST run inside the same REPEATABLE READ transaction
// as every other pull query in the same request (internal/sync's pull
// service opens it), so pg_current_snapshot() resolves to one stable
// snapshot across all of them.
func (q *Queries) ListActivityEventChangesForUser(ctx context.Context, arg ListActivityEventChangesForUserParams) ([]ListActivityEventChangesForUserRow, error) {
	rows, err := q.db.Query(ctx, listActivityEventChangesForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityEventChangesForUserRow
	for rows.Next() {
		var i ListActivityEventChangesForUserRow
		if err := rows.Scan(
			&i.EventID,
			&i.StartedAt,
			&i.EndedAt,
			&i.AppBundleID,
			&i.CategoryName,
			&i.Precision,
			&i.Deleted,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryChangesForUser = `-- name: ListCategoryChangesForUser :many
SELECT id, user_id, name, color, productivity, updated_at, deleted_at, server_seq
FROM categories
WHERE (user_id = $1 OR user_id IS NULL) AND server_seq > $2 AND xid_before_snapshot_horizon(xmin)
ORDER BY server_seq ASC
LIMIT $3
`

type ListCategoryChangesForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

type ListCategoryChangesForUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	Color        string             `json:"color"`
	Productivity int16              `json:"productivity"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq    int64              `json:"server_seq"`
}

// One page of GET /v1/sync/changes's "categories" entity (RIZ-34 M1).
// database-schema.md states server_seq-based keyset pagination applies to
// categories exactly like every other syncable table; scoping mirrors
// internal/store/queries/categories.sql's ListCategoriesForUser: a user's
// pull sees the union of every system default category (user_id IS NULL)
// plus their own custom categories (user_id = $1), so a client can resolve
// every category_id it might see on an activity_event/user_app_setting
// row. See ListActivityEventChangesForUser's doc comment for the
// xmin-horizon rationale.
func (q *Queries) ListCategoryChangesForUser(ctx context.Context, arg ListCategoryChangesForUserParams) ([]ListCategoryChangesForUserRow, error) {
	rows, err := q.db.Query(ctx, listCategoryChangesForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryChangesForUserRow
	for rows.Next() {
		var i ListCategoryChangesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Productivity,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFocusSessionChangesForUser = `-- name: ListFocusSessionChangesForUser :many
SELECT id, project_id, kind, planned_duration_s, started_at, ended_at,
       status, note, updated_at, deleted_at, server_seq
FROM focus_sessions
WHERE user_id = $1 AND server_seq > $2 AND xid_before_snapshot_horizon(xmin)
ORDER BY server_seq ASC
LIMIT $3
`

type ListFocusSessionChangesForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

type ListFocusSessionChangesForUserRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Kind             string             `json:"kind"`
	PlannedDurationS *int32             `json:"planned_duration_s"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	Status           string             `json:"status"`
	Note             *string            `json:"note"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq        int64              `json:"server_seq"`
}

// One page of GET /v1/sync/changes's "focus_sessions" entity. See
// ListActivityEventChangesForUser's doc comment for the pagination,
// tenant-scoping, and xmin-horizon rationale, which applies identically
// here.
func (q *Queries) ListFocusSessionChangesForUser(ctx context.Context, arg ListFocusSessionChangesForUserParams) ([]ListFocusSessionChangesForUserRow, error) {
	rows, err := q.db.Query(ctx, listFocusSessionChangesForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFocusSessionChangesForUserRow
	for rows.Next() {
		var i ListFocusSessionChangesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.PlannedDurationS,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.Note,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectChangesForUser = `-- name: ListProjectChangesForUser :many
SELECT id, name, color, archived_at, updated_at, deleted_at, server_seq
FROM projects
WHERE user_id = $1 AND server_seq > $2 AND xid_before_snapshot_horizon(xmin)
ORDER BY server_seq ASC
LIMIT $3
`

type ListProjectChangesForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

type ListProjectChangesForUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Color      string             `json:"color"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq  int64              `json:"server_seq"`
}

// One page of GET /v1/sync/changes's "projects" entity. See
// ListActivityEventChangesForUser's doc comment for the xmin-horizon
// rationale.
func (q *Queries) ListProjectChangesForUser(ctx context.Context, arg ListProjectChangesForUserParams) ([]ListProjectChangesForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectChangesForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectChangesForUserRow
	for rows.Next() {
		var i ListProjectChangesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.ArchivedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagChangesForUser = `-- name: ListTagChangesForUser :many
SELECT id, name, updated_at, deleted_at, server_seq
FROM tags
WHERE user_id = $1 AND server_seq > $2 AND xid_before_snapshot_horizon(xmin)
ORDER BY server_seq ASC
LIMIT $3
`

type ListTagChangesForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

type ListTagChangesForUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq int64              `json:"server_seq"`
}

// One page of GET /v1/sync/changes's "tags" entity. See
// ListActivityEventChangesForUser's doc comment for the xmin-horizon
// rationale.
func (q *Queries) ListTagChangesForUser(ctx context.Context, arg ListTagChangesForUserParams) ([]ListTagChangesForUserRow, error) {
	rows, err := q.db.Query(ctx, listTagChangesForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagChangesForUserRow
	for rows.Next() {
		var i ListTagChangesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAppSettingChangesForUser = `-- name: ListUserAppSettingChangesForUser :many
SELECT user_id, app_id, category_id, excluded, updated_at, server_seq
FROM user_app_settings
WHERE user_id = $1 AND server_seq > $2 AND xid_before_snapshot_horizon(xmin)
ORDER BY server_seq ASC
LIMIT $3
`

type ListUserAppSettingChangesForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

// One page of GET /v1/sync/changes's "user_app_settings" entity.
// user_app_settings has no deleted_at/deleted column (see
// documentation/database-schema.md), so every row from this query is an
// upsert; internal/sync's pull service always reports an empty
// "tombstones" array for this entity type. See
// ListActivityEventChangesForUser's doc comment for the xmin-horizon
// rationale.
func (q *Queries) ListUserAppSettingChangesForUser(ctx context.Context, arg ListUserAppSettingChangesForUserParams) ([]UserAppSetting, error) {
	rows, err := q.db.Query(ctx, listUserAppSettingChangesForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAppSetting
	for rows.Next() {
		var i UserAppSetting
		if err := rows.Scan(
			&i.UserID,
			&i.AppID,
			&i.CategoryID,
			&i.Excluded,
			&i.UpdatedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
