// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivityEventForChangelogEntry = `-- name: GetActivityEventForChangelogEntry :one
SELECT
    ae.event_id,
    ae.user_id,
    ae.started_at,
    ae.ended_at,
    a.bundle_id AS app_bundle_id,
    c.name AS category_name,
    ae.precision,
    ae.deleted,
    ae.server_seq
FROM activity_events ae
LEFT JOIN apps a ON a.id = ae.app_id
LEFT JOIN categories c ON c.id = ae.category_id
WHERE ae.user_id = $1 AND ae.event_id = $2 AND ae.started_at = $3
`

type GetActivityEventForChangelogEntryParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	EventID   pgtype.UUID        `json:"event_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

type GetActivityEventForChangelogEntryRow struct {
	EventID      pgtype.UUID        `json:"event_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	EndedAt      pgtype.Timestamptz `json:"ended_at"`
	AppBundleID  *string            `json:"app_bundle_id"`
	CategoryName *string            `json:"category_name"`
	Precision    string             `json:"precision"`
	Deleted      bool               `json:"deleted"`
	ServerSeq    int64              `json:"server_seq"`
}

// Resolves a sync_changelog 'activity_events' entry to the entity's current
// state, per internal/sync/pull.go's per-page dedupe-then-resolve step.
// Binds started_at (the hypertable's partitioning column, carried on the
// changelog row precisely so this lookup can supply it) in addition to
// user_id/event_id: ordinary (non-system-column) reads against a
// compressed chunk are fully supported by TimescaleDB -- only a bare
// system-column reference (this query has none) is restricted -- so this
// lookup succeeds unconditionally, including against a compressed chunk,
// which is the entire point of this migration's pivot away from querying
// activity_events.xmin directly. Zero rows is possible (see pull.go's doc
// comment on why that's safe to skip) but not expected in steady state:
// activity_events rows are never hard-deleted.
func (q *Queries) GetActivityEventForChangelogEntry(ctx context.Context, arg GetActivityEventForChangelogEntryParams) (GetActivityEventForChangelogEntryRow, error) {
	row := q.db.QueryRow(ctx, getActivityEventForChangelogEntry, arg.UserID, arg.EventID, arg.StartedAt)
	var i GetActivityEventForChangelogEntryRow
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.AppBundleID,
		&i.CategoryName,
		&i.Precision,
		&i.Deleted,
		&i.ServerSeq,
	)
	return i, err
}

const getCategoryForChangelogEntry = `-- name: GetCategoryForChangelogEntry :one
SELECT id, user_id, name, color, productivity, updated_at, deleted_at, server_seq
FROM categories
WHERE id = $1 AND (user_id = $2 OR user_id IS NULL)
`

type GetCategoryForChangelogEntryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetCategoryForChangelogEntryRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	Color        string             `json:"color"`
	Productivity int16              `json:"productivity"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq    int64              `json:"server_seq"`
}

// Resolves a sync_changelog 'categories' entry to the entity's current
// state. `(user_id = $2 OR user_id IS NULL)` mirrors the old
// ListCategoryChangesForUser's scoping: a category row's own user_id
// always matches the changelog row's user_id that produced the entry
// (both NULL for a system default, both set to the same owner otherwise),
// so this is a tenant-safe point lookup, not a broadening of scope.
func (q *Queries) GetCategoryForChangelogEntry(ctx context.Context, arg GetCategoryForChangelogEntryParams) (GetCategoryForChangelogEntryRow, error) {
	row := q.db.QueryRow(ctx, getCategoryForChangelogEntry, arg.ID, arg.UserID)
	var i GetCategoryForChangelogEntryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Productivity,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getFocusSessionForChangelogEntry = `-- name: GetFocusSessionForChangelogEntry :one
SELECT id, project_id, kind, planned_duration_s, started_at, ended_at,
       status, note, updated_at, deleted_at, server_seq
FROM focus_sessions
WHERE user_id = $1 AND id = $2
`

type GetFocusSessionForChangelogEntryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetFocusSessionForChangelogEntryRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Kind             string             `json:"kind"`
	PlannedDurationS *int32             `json:"planned_duration_s"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	Status           string             `json:"status"`
	Note             *string            `json:"note"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq        int64              `json:"server_seq"`
}

// Resolves a sync_changelog 'focus_sessions' entry to the entity's current
// state. See GetActivityEventForChangelogEntry's doc comment for the
// resolve-step rationale.
func (q *Queries) GetFocusSessionForChangelogEntry(ctx context.Context, arg GetFocusSessionForChangelogEntryParams) (GetFocusSessionForChangelogEntryRow, error) {
	row := q.db.QueryRow(ctx, getFocusSessionForChangelogEntry, arg.UserID, arg.ID)
	var i GetFocusSessionForChangelogEntryRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.PlannedDurationS,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Note,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getProjectForChangelogEntry = `-- name: GetProjectForChangelogEntry :one
SELECT id, name, color, archived_at, updated_at, deleted_at, server_seq
FROM projects
WHERE user_id = $1 AND id = $2
`

type GetProjectForChangelogEntryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetProjectForChangelogEntryRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Color      string             `json:"color"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq  int64              `json:"server_seq"`
}

// Resolves a sync_changelog 'projects' entry to the entity's current state.
// See GetActivityEventForChangelogEntry's doc comment for the
// resolve-step rationale.
func (q *Queries) GetProjectForChangelogEntry(ctx context.Context, arg GetProjectForChangelogEntryParams) (GetProjectForChangelogEntryRow, error) {
	row := q.db.QueryRow(ctx, getProjectForChangelogEntry, arg.UserID, arg.ID)
	var i GetProjectForChangelogEntryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.ArchivedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getTagForChangelogEntry = `-- name: GetTagForChangelogEntry :one
SELECT id, name, updated_at, deleted_at, server_seq
FROM tags
WHERE user_id = $1 AND id = $2
`

type GetTagForChangelogEntryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetTagForChangelogEntryRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ServerSeq int64              `json:"server_seq"`
}

// Resolves a sync_changelog 'tags' entry to the entity's current state. See
// GetActivityEventForChangelogEntry's doc comment for the resolve-step
// rationale.
func (q *Queries) GetTagForChangelogEntry(ctx context.Context, arg GetTagForChangelogEntryParams) (GetTagForChangelogEntryRow, error) {
	row := q.db.QueryRow(ctx, getTagForChangelogEntry, arg.UserID, arg.ID)
	var i GetTagForChangelogEntryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getUserAppSettingForChangelogEntry = `-- name: GetUserAppSettingForChangelogEntry :one
SELECT user_id, app_id, category_id, excluded, updated_at, server_seq
FROM user_app_settings
WHERE user_id = $1 AND app_id = $2
`

type GetUserAppSettingForChangelogEntryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	AppID  pgtype.UUID `json:"app_id"`
}

// Resolves a sync_changelog 'user_app_settings' entry to the entity's
// current state. entity_id on the changelog row is app_id (this table's
// primary key is the composite (user_id, app_id); user_id is already the
// changelog row's own user_id column, per migration 000026's comment). No
// tombstone path: user_app_settings has no deleted_at/deleted column (see
// documentation/database-schema.md), so every resolved row is an upsert.
func (q *Queries) GetUserAppSettingForChangelogEntry(ctx context.Context, arg GetUserAppSettingForChangelogEntryParams) (UserAppSetting, error) {
	row := q.db.QueryRow(ctx, getUserAppSettingForChangelogEntry, arg.UserID, arg.AppID)
	var i UserAppSetting
	err := row.Scan(
		&i.UserID,
		&i.AppID,
		&i.CategoryID,
		&i.Excluded,
		&i.UpdatedAt,
		&i.ServerSeq,
	)
	return i, err
}

const listChangelogPage = `-- name: ListChangelogPage :many
SELECT
    changelog_id,
    user_id,
    entity_type,
    entity_id,
    event_started_at,
    server_seq,
    xmin_xid8(xmin) AS xid8
FROM sync_changelog
WHERE (user_id = $1 OR user_id IS NULL)
    AND xmin_xid8(xmin) < pg_snapshot_xmin(pg_current_snapshot())
    AND (xmin_xid8(xmin), server_seq) > ($2::xid8, $3::bigint)
ORDER BY xmin_xid8(xmin) ASC, server_seq ASC
LIMIT $4
`

type ListChangelogPageParams struct {
	UserID     pgtype.UUID   `json:"user_id"`
	CursorXid8 pgtype.Uint64 `json:"cursor_xid8"`
	CursorSeq  int64         `json:"cursor_seq"`
	PageLimit  int32         `json:"page_limit"`
}

type ListChangelogPageRow struct {
	ChangelogID    int64              `json:"changelog_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	EventStartedAt pgtype.Timestamptz `json:"event_started_at"`
	ServerSeq      int64              `json:"server_seq"`
	Xid8           pgtype.Uint64      `json:"xid8"`
}

// One page of GET /v1/sync/changes's raw change feed, per
// documentation/sync-protocol.md §Pull. RIZ-34 (pivot): this single query
// replaces the six separate per-entity-table pagination queries this file
// used to define (ListActivityEventChangesForUser and friends), which
// paginated each syncable table directly by its own
// (xmin_xid8(xmin), server_seq) tuple -- fatal for activity_events, a
// compressed hypertable that rejects any xmin reference on a compressed
// chunk. See migration 000026's header comment for the full rationale.
//
// Pagination/ordering key is still the tuple
// (xmin_xid8(sync_changelog.xmin), server_seq) migration 000025
// established -- unchanged in shape, just anchored to sync_changelog's own
// xmin (a plain, never-compressed heap table) instead of each entity
// table's. xmin_xid8(xmin) < pg_snapshot_xmin(pg_current_snapshot()) is the
// same horizon gate as before: only changelog rows whose inserting
// transaction is fully, permanently committed as of this pull's MVCC
// snapshot are delivered, so a page can never include a row whose
// transaction might still be in flight (see migration 000024's comment for
// the full invariant). cursor_xid8/cursor_seq are the caller's opaque
// cursor's decoded (xid8, server_seq) tuple; page_limit is the
// caller-requested page size PLUS ONE (see internal/sync/pull.go), so the
// caller can detect "more rows exist beyond this page" without a second
// round trip.
//
// `(user_id = $1 OR user_id IS NULL)` mirrors ListCategoryChangesForUser's
// old scoping (a category's changelog row has user_id NULL exactly when
// the category itself is a system default): every other entity type's
// changelog rows always have user_id set to the actual owner, so this
// OR only ever matches system-category rows in practice, never leaking a
// non-category row across tenants.
//
// This query MUST run inside the same REPEATABLE READ transaction as the
// rest of a single pull request (internal/sync/pull.go opens it), so
// pg_current_snapshot() resolves to one stable snapshot for the horizon
// gate.
func (q *Queries) ListChangelogPage(ctx context.Context, arg ListChangelogPageParams) ([]ListChangelogPageRow, error) {
	rows, err := q.db.Query(ctx, listChangelogPage,
		arg.UserID,
		arg.CursorXid8,
		arg.CursorSeq,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangelogPageRow
	for rows.Next() {
		var i ListChangelogPageRow
		if err := rows.Scan(
			&i.ChangelogID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.EventStartedAt,
			&i.ServerSeq,
			&i.Xid8,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
