// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Advances the single sync_changelog_horizon row to the maximum of its
	// current (horizon_xid8, horizon_server_seq) and the caller-supplied
	// values (the max xid8/server_seq among the batch just deleted). GREATEST
	// (rather than an unconditional SET) makes this safe to call with a batch
	// whose max happens to be behind the already-recorded horizon — which
	// cannot happen in the normal single-pruner-instance case (batches are
	// processed in changelog_id order, which is also non-decreasing in
	// (xid8, server_seq) per migration 000025's gap-free-by-construction
	// invariant) but keeps this query correct/idempotent under retry or a
	// hypothetical second pruner instance rather than relying on that
	// invariant to hold at the call site too.
	AdvanceChangelogHorizon(ctx context.Context, arg AdvanceChangelogHorizonParams) (AdvanceChangelogHorizonRow, error)
	// Closed-period fast path for reports/apps: sums the daily_app_totals
	// continuous aggregate over [from_day, to_day) per
	// documentation/architecture-backend.md §Aggregation Strategy. Only used
	// when the request has no device_id/precision filter — see
	// internal/reports/service.go.
	//
	// Same per-device window-capping as CategoryTotalsForRange above, using
	// daily_app_totals' device_id column (migration 000034) — an upper bound
	// on same-device overlap inflation for closed periods, not a
	// reproduction of the raw path's exact interval merge. See
	// CategoryTotalsForRange's comment for the worked counterexample where
	// the two paths diverge. window_seconds must be > 0 for the same reason
	// noted there.
	AppTotalsForRange(ctx context.Context, arg AppTotalsForRangeParams) ([]AppTotalsForRangeRow, error)
	// Closed-period fast path for reports/daily, reports/categories, and
	// reports/summary's category breakdown: sums the daily_category_totals
	// continuous aggregate over [from_day, to_day) per
	// documentation/architecture-backend.md §Aggregation Strategy. Only used
	// when the request has no device_id/precision filter — see
	// internal/reports/service.go.
	//
	// Bounds (does NOT reproduce) the raw-event path's same-device overlap
	// handling (documentation/sync-protocol.md §Overlap Rules;
	// internal/reports/trim.go implements the actual interval merge for raw
	// events): daily_category_totals is grouped by device_id (migration
	// 000035), so each device's total_s is first summed across the requested
	// days, then capped at window_seconds — the length of [from_day, to_day)
	// in seconds — before being added into the category total. This is an
	// UPPER BOUND on same-device overlap inflation, not the raw path's exact
	// merged duration: the cap only removes overlap that pushes a device's
	// naive summed total_s above the window's own length, so it agrees with
	// the raw path exactly when a device's merged coverage spans the whole
	// window, but can still overstate the total otherwise. For example, over
	// a 24h window with same-device events covering 00:00-06:00 and
	// 03:00-09:00 (merged coverage 9h, naive sum 12h), the raw path returns
	// 9h while this query returns min(12h, 24h) = 12h. Cross-device overlap
	// is still not trimmed either way: each device's capped total is summed
	// into the category total independently, same as the raw path.
	// window_seconds must be > 0 (validated by the caller — see
	// internal/reports/dimension.go's windowSeconds) so LEAST(x, 0) can't
	// silently zero every total.
	CategoryTotalsForRange(ctx context.Context, arg CategoryTotalsForRangeParams) ([]CategoryTotalsForRangeRow, error)
	// Auto-creates an apps row the first time a bundle_id/platform pair is
	// observed during ingestion, per documentation/architecture-backend.md
	// §Ingestion Pipeline ("if no matching row exists, one is created
	// automatically"). ON CONFLICT DO NOTHING (rather than erroring) makes this
	// safe to call optimistically under a race with a concurrent ingestion of
	// the same new bundle_id/platform; a caller that gets zero rows back must
	// re-fetch via GetAppByBundleID.
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	// POST /v1/categories always creates a user-owned category (user_id set to
	// the authenticated caller); a client cannot create a system default
	// through this endpoint. id is server-generated (gen_random_uuid()): per
	// documentation/database-schema.md's PK convention, categories are not in
	// the client-supplied-UUIDv7 list (only activity_events, focus_sessions,
	// projects, and tags are).
	CreateCategoryForUser(ctx context.Context, arg CreateCategoryForUserParams) (Category, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	// POST /v1/focus-sessions per documentation/api-reference.md §CRUD groups.
	// id is caller-supplied (client-supplied-UUIDv7 entity per
	// documentation/database-schema.md's PK convention, same as
	// internal/sync's push-side UpsertFocusSession). device_id and project_id
	// are validated by the caller (internal/focussessions's service) against
	// the authenticated user before this INSERT runs, per
	// documentation/security.md §Tenant Isolation — device_id is NOT NULL on
	// this table (see documentation/database-schema.md's focus_sessions),
	// so a caller must resolve a device it owns first.
	CreateFocusSessionForUser(ctx context.Context, arg CreateFocusSessionForUserParams) (FocusSession, error)
	// Creates a project owned by the authenticated user, per
	// documentation/api-reference.md §CRUD groups ("POST /v1/projects"). id is
	// supplied by the caller (see internal/projects's uuid handling): per
	// documentation/database-schema.md's PK convention, projects are a
	// client-supplied-UUIDv7 entity like tags/focus_sessions, whether the row
	// originates from a sync push or a direct REST create — this query does
	// not itself generate one.
	CreateProjectForUser(ctx context.Context, arg CreateProjectForUserParams) (Project, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// Creates a tag owned by the authenticated user, per
	// documentation/api-reference.md §CRUD groups ("POST /v1/tags"). A
	// concurrent/duplicate name for the same user surfaces as a unique
	// violation on tags' UNIQUE (user_id, name) constraint, mapped by the
	// caller via store.ConstraintViolation to a 409 Conflict.
	CreateTagForUser(ctx context.Context, arg CreateTagForUserParams) (Tag, error)
	// Callers pass the desired role explicitly ('user' by default); the
	// database-side DEFAULT 'user' on this column only applies when the column
	// is omitted from an INSERT's column list, which sqlc's generated,
	// fully-columned INSERT never does.
	//
	// server_seq is intentionally omitted from the column list: the
	// users_set_server_seq BEFORE INSERT trigger (see migration 000022)
	// unconditionally assigns it from the shared server_seq_global sequence,
	// keeping every syncable table's server_seq drawn from the same global
	// sequence space per documentation/sync-protocol.md.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes exactly the rows SelectChangelogPruneBatch identified, by their
	// changelog_id primary keys, in the SAME transaction as that select. Using
	// the exact id set (rather than re-evaluating the created_at < cutoff
	// predicate a second time) means this DELETE can never race with a
	// concurrent write that inserted a new, unrelated row after the select ran
	// but before the delete executes — it only ever touches the exact rows
	// already identified as prune candidates.
	DeleteChangelogRows(ctx context.Context, changelogIds []int64) (int64, error)
	// Resolves a sync_changelog 'activity_events' entry to the entity's current
	// state, per internal/sync/pull.go's per-page dedupe-then-resolve step.
	// Binds started_at (the hypertable's partitioning column, carried on the
	// changelog row precisely so this lookup can supply it) in addition to
	// user_id/event_id: ordinary (non-system-column) reads against a
	// compressed chunk are fully supported by TimescaleDB -- only a bare
	// system-column reference (this query has none) is restricted -- so this
	// lookup succeeds unconditionally, including against a compressed chunk,
	// which is the entire point of this migration's pivot away from querying
	// activity_events.xmin directly. Zero rows is possible (see pull.go's doc
	// comment on why that's safe to skip) but not expected in steady state:
	// activity_events rows are never hard-deleted.
	GetActivityEventForChangelogEntry(ctx context.Context, arg GetActivityEventForChangelogEntryParams) (GetActivityEventForChangelogEntryRow, error)
	// Looks up the global app-catalog row for a (bundle_id, platform) pair, per
	// documentation/database-schema.md's `UNIQUE (bundle_id, platform)` on
	// `apps`. Not user-scoped: the catalog is global/cross-user by design (see
	// documentation/architecture-backend.md §Ingestion Pipeline, stage 2).
	GetAppByBundleID(ctx context.Context, arg GetAppByBundleIDParams) (App, error)
	// Resolves a sync_changelog 'categories' entry to the entity's current
	// state. `(user_id = $2 OR user_id IS NULL)` mirrors the old
	// ListCategoryChangesForUser's scoping: a category row's own user_id
	// always matches the changelog row's user_id that produced the entry
	// (both NULL for a system default, both set to the same owner otherwise),
	// so this is a tenant-safe point lookup, not a broadening of scope.
	GetCategoryForChangelogEntry(ctx context.Context, arg GetCategoryForChangelogEntryParams) (GetCategoryForChangelogEntryRow, error)
	// GET /v1/categories/{id}: readable if it's a system default or the
	// caller's own, per database-schema.md's categories.user_id semantics.
	GetCategoryForUser(ctx context.Context, arg GetCategoryForUserParams) (Category, error)
	// Reads the current retained horizon, per internal/sync/pull.go's
	// cursor-reset check: a pull whose caller-supplied cursor is strictly
	// below this position cannot be served a gap-free page (rows between its
	// cursor and here were deleted by age-based retention) and must be told to
	// reset instead. Called inside the same REPEATABLE READ, READ ONLY
	// transaction as the rest of a pull (runInPullSnapshot) so the horizon
	// check and the changelog page read observe one consistent snapshot.
	GetChangelogHorizon(ctx context.Context) (GetChangelogHorizonRow, error)
	// Scoped by user_id per documentation/security.md §Tenant Isolation: every
	// query is scoped by user_id from the access token, so a request
	// authenticated as one user can never read another user's device row.
	GetDeviceByID(ctx context.Context, arg GetDeviceByIDParams) (Device, error)
	// Unscoped-by-user lookup used only to distinguish, after an
	// UpsertFocusSession call returns zero rows, whether the existing row
	// under this id belongs to a different user entirely (a tenant-isolation
	// violation, reported as "invalid") from a same-user last-write-wins loss
	// (reported as "duplicate") — see internal/sync's push service.
	GetFocusSessionByID(ctx context.Context, id pgtype.UUID) (FocusSession, error)
	// Resolves a sync_changelog 'focus_sessions' entry to the entity's current
	// state. See GetActivityEventForChangelogEntry's doc comment for the
	// resolve-step rationale.
	GetFocusSessionForChangelogEntry(ctx context.Context, arg GetFocusSessionForChangelogEntryParams) (GetFocusSessionForChangelogEntryRow, error)
	// Tenant-scoped lookup for GET /v1/focus-sessions/{id} and as the
	// authorization check before PATCH/DELETE. Zero rows for either "no such
	// session" or "belongs to another user," reported identically as 404.
	GetFocusSessionForUser(ctx context.Context, arg GetFocusSessionForUserParams) (FocusSession, error)
	// Authorization check used before UPDATE/DELETE: unlike GetCategoryForUser,
	// this only matches a category the caller owns (user_id = $2), never a
	// system default (user_id IS NULL). System categories are read-only via
	// the API — see internal/categories's service doc comment for why an
	// attempt to PATCH/DELETE one is reported as 404 rather than 403, matching
	// the cross-tenant 404-equivalence convention used elsewhere in this
	// ticket.
	GetOwnCategoryForUser(ctx context.Context, arg GetOwnCategoryForUserParams) (Category, error)
	// Tenant-scoped existence check for a client-supplied focus_session
	// project_id, per documentation/security.md §Tenant Isolation: a project_id
	// is only accepted if it both exists and belongs to the authenticated
	// user_id, so user A can never reference user B's project (an FK violation
	// alone only proves the row exists somewhere, not that it's the caller's).
	// Zero rows for either reason (missing entirely, or owned by someone else)
	// so the caller cannot distinguish "doesn't exist" from "not yours" and
	// leak the other tenant's project existence.
	GetProjectByIDForUser(ctx context.Context, arg GetProjectByIDForUserParams) (Project, error)
	// Resolves a sync_changelog 'projects' entry to the entity's current state.
	// See GetActivityEventForChangelogEntry's doc comment for the
	// resolve-step rationale.
	GetProjectForChangelogEntry(ctx context.Context, arg GetProjectForChangelogEntryParams) (GetProjectForChangelogEntryRow, error)
	// Tenant-scoped lookup for GET /v1/projects/{id}, and the authorization
	// check before PATCH/DELETE. Unlike sync.sql's GetProjectByIDForUser (used
	// by the push path to validate a focus_session's project_id reference,
	// where a soft-deleted project should arguably still resolve — that
	// existing behavior is out of scope for this ticket and left unchanged),
	// this query excludes soft-deleted rows: a deleted project must read back
	// as 404, matching documentation/database-schema.md's soft-delete
	// convention and this ticket's cross-tenant/deleted 404-equivalence
	// convention.
	GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (Project, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	// Blocking row lock, used only after GetRefreshTokenByHashForUpdateNoWait
	// has detected contention: waits for the concurrently in-flight rotation to
	// commit, then returns the now-serialized, final row state (RIZ-32 M2).
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	// Locks the refresh token row without blocking (SQLSTATE 55P03
	// lock_not_available if another transaction already holds the lock), so the
	// caller can distinguish "I am racing a concurrently in-flight rotation of
	// this exact token" from "I am the only one looking at this row right now",
	// per documentation/security.md's refresh-rotation flow (RIZ-32 M2).
	GetRefreshTokenByHashForUpdateNoWait(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	// Resolves a sync_changelog 'tags' entry to the entity's current state. See
	// GetActivityEventForChangelogEntry's doc comment for the resolve-step
	// rationale.
	GetTagForChangelogEntry(ctx context.Context, arg GetTagForChangelogEntryParams) (GetTagForChangelogEntryRow, error)
	// Tenant-scoped lookup for GET /v1/tags/{id}. Zero rows for either "no
	// such tag" or "belongs to another user," per
	// documentation/security.md §Tenant Isolation, so the two cases are
	// reported identically as 404.
	GetTagForUser(ctx context.Context, arg GetTagForUserParams) (Tag, error)
	// The user-specific override consulted by category resolution's first
	// fallback step, per documentation/architecture-backend.md §Ingestion
	// Pipeline stage 3. Scoped by user_id per documentation/security.md
	// §Tenant Isolation.
	GetUserAppSettingByUserAndApp(ctx context.Context, arg GetUserAppSettingByUserAndAppParams) (UserAppSetting, error)
	// Resolves a sync_changelog 'user_app_settings' entry to the entity's
	// current state. entity_id on the changelog row is app_id (this table's
	// primary key is the composite (user_id, app_id); user_id is already the
	// changelog row's own user_id column, per migration 000026's comment). No
	// tombstone path: user_app_settings has no deleted_at/deleted column (see
	// documentation/database-schema.md), so every resolved row is an upsert.
	GetUserAppSettingForChangelogEntry(ctx context.Context, arg GetUserAppSettingForChangelogEntryParams) (UserAppSetting, error)
	GetUserByAppleUserID(ctx context.Context, appleUserID *string) (User, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Idempotent insert for the append-only activity_events hypertable, per
	// documentation/sync-protocol.md §Entity Classes ("Idempotency key is the
	// composite UNIQUE (user_id, event_id, started_at) constraint"). ON
	// CONFLICT DO NOTHING means a retried/replayed push of the same event
	// returns zero rows, which the caller reports as a "duplicate" per-item
	// result rather than an error. Scoped by user_id (the row is created for
	// the authenticated caller only, never for a user_id supplied by the
	// request body) per documentation/security.md §Tenant Isolation.
	InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (ActivityEvent, error)
	ListActiveRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error)
	// GET /v1/activities per documentation/api-reference.md §Activities &
	// reports: raw tracked events for the authenticated user, filterable by
	// time range, app, category, project, device, and precision. Scoped by
	// user_id per documentation/security.md §Tenant Isolation. Soft-deleted
	// (deleted = true) rows are excluded, matching the CRUD groups' convention
	// of excluding tombstoned rows from a "current state" list.
	//
	// Keyset-paginated on (started_at, event_id) ascending rather than the
	// server_seq cursor other CRUD lists use: an activity-events list is
	// naturally consumed in chronological order over an explicit time range,
	// and started_at is the hypertable's own partitioning column, so ordering
	// on it lets Postgres use the activity_events_user_started_idx index
	// instead of the server_seq index. The initial page passes
	// cursor_started_at = '-infinity' and cursor_event_id =
	// '00000000-0000-0000-0000-000000000000' (see internal/activities'
	// cursor.go), which sorts before every real row.
	//
	// sqlc.narg filters: a NULL argument (an omitted query-string filter)
	// disables that filter's predicate entirely via the "IS NULL OR" branch.
	ListActivityEventsForUser(ctx context.Context, arg ListActivityEventsForUserParams) ([]ActivityEvent, error)
	// GET /v1/categories per documentation/api-reference.md §CRUD groups.
	// documentation/database-schema.md's categories table: "user_id IS NULL
	// denotes a system default category available to every user; user_id set
	// denotes a user's own custom category" — so the list a user sees is the
	// union of every system default plus their own custom categories,
	// keyset-paginated together by server_seq.
	ListCategoriesForUser(ctx context.Context, arg ListCategoriesForUserParams) ([]Category, error)
	// One page of GET /v1/sync/changes's raw change feed, per
	// documentation/sync-protocol.md §Pull. RIZ-34 (pivot): this single query
	// replaces the six separate per-entity-table pagination queries this file
	// used to define (ListActivityEventChangesForUser and friends), which
	// paginated each syncable table directly by its own
	// (xmin_xid8(xmin), server_seq) tuple -- fatal for activity_events, a
	// compressed hypertable that rejects any xmin reference on a compressed
	// chunk. See migration 000026's header comment for the full rationale.
	//
	// Pagination/ordering key is still the tuple
	// (xmin_xid8(sync_changelog.xmin), server_seq) migration 000025
	// established -- unchanged in shape, just anchored to sync_changelog's own
	// xmin (a plain, never-compressed heap table) instead of each entity
	// table's. xmin_xid8(xmin) < pg_snapshot_xmin(pg_current_snapshot()) is the
	// same horizon gate as before: only changelog rows whose inserting
	// transaction is fully, permanently committed as of this pull's MVCC
	// snapshot are delivered, so a page can never include a row whose
	// transaction might still be in flight (see migration 000024's comment for
	// the full invariant). cursor_xid8/cursor_seq are the caller's opaque
	// cursor's decoded (xid8, server_seq) tuple; page_limit is the
	// caller-requested page size PLUS ONE (see internal/sync/pull.go), so the
	// caller can detect "more rows exist beyond this page" without a second
	// round trip.
	//
	// `(user_id = $1 OR user_id IS NULL)` mirrors ListCategoryChangesForUser's
	// old scoping (a category's changelog row has user_id NULL exactly when
	// the category itself is a system default): every other entity type's
	// changelog rows always have user_id set to the actual owner, so this
	// OR only ever matches system-category rows in practice, never leaking a
	// non-category row across tenants.
	//
	// This query MUST run inside the same REPEATABLE READ transaction as the
	// rest of a single pull request (internal/sync/pull.go opens it), so
	// pg_current_snapshot() resolves to one stable snapshot for the horizon
	// gate.
	ListChangelogPage(ctx context.Context, arg ListChangelogPageParams) ([]ListChangelogPageRow, error)
	ListDevicesByUser(ctx context.Context, userID pgtype.UUID) ([]Device, error)
	// Keyset-paginated list for GET /v1/focus-sessions, per
	// documentation/api-reference.md §Conventions. Scoped by user_id per
	// documentation/security.md §Tenant Isolation; excludes soft-deleted rows.
	ListFocusSessionsForUser(ctx context.Context, arg ListFocusSessionsForUserParams) ([]FocusSession, error)
	// Keyset-paginated list for GET /v1/projects, per
	// documentation/api-reference.md §Conventions ("list endpoints ... use a
	// cursor-based convention"). Soft-deleted rows are excluded: a CRUD list is
	// "your current projects," not the sync tombstone stream (GET
	// /v1/sync/changes serves that). Scoped by user_id per
	// documentation/security.md §Tenant Isolation.
	ListProjectsForUser(ctx context.Context, arg ListProjectsForUserParams) ([]Project, error)
	// Keyset-paginated list for GET /v1/tags, per
	// documentation/api-reference.md §Conventions. Scoped by user_id per
	// documentation/security.md §Tenant Isolation; excludes soft-deleted rows.
	ListTagsForUser(ctx context.Context, arg ListTagsForUserParams) ([]Tag, error)
	// The report layer's raw-event pass, per documentation/architecture-backend.md
	// §Aggregation Strategy: used (a) always for the current/partial period,
	// and (b) as the only path for filters (device_id, precision) or
	// dimensions (project) the continuous aggregates cannot serve. As of
	// migrations 000034-000036, daily_app_totals/daily_category_totals do
	// carry a device_id column, but CategoryTotalsForRange/AppTotalsForRange
	// below only use it for a same-device overlap *cap* (a window-length
	// upper bound, not an exact merge — see those queries' comments); neither
	// query can honor an explicit device_id filter or a precision filter (no
	// precision column exists on any cagg), and no project-dimensioned
	// aggregate exists at all, so a device_id/precision-filtered or
	// project-dimensioned request still falls back to this raw pass — see
	// internal/reports' service.go doc comment for the full resolution.
	//
	// Selects events overlapping [from_ts, to_ts) — not merely started within
	// it — so an event that begins before the window and ends inside it (or
	// vice versa) is still included for trimming, which clips each event to
	// the window before merging. Joins apps/categories/projects so the report
	// layer never needs a second round trip to resolve display names.
	RawActivityEventsForReport(ctx context.Context, arg RawActivityEventsForReportParams) ([]RawActivityEventsForReportRow, error)
	// Atomically records a failed password check against an existing account
	// and, if the post-increment attempt count reaches @threshold, escalates
	// into (or re-escalates) a lockout — per RIZ-59 / documentation/security.md
	// §API hardening ("brute-force lockout on login").
	//
	// Everything is computed from the row's own current values inside this
	// single UPDATE statement (failed_login_attempts, lockout_count), rather
	// than read in Go and written back separately, so concurrent logins
	// against the same account can never race a read-modify-write: Postgres's
	// row-level write lock on this UPDATE serializes concurrent callers, and
	// each one sees the effect of the previous one's commit.
	//
	// The lockout duration is base_duration_seconds doubled once per prior
	// lockout (lockout_count, read BEFORE this attempt's own increment),
	// capped at max_duration_seconds. The doubling/capping arithmetic is done
	// entirely in the seconds (float8) domain — LEAST() runs BEFORE the value
	// is ever converted to an interval — because converting the uncapped
	// doubled value to an interval first can overflow Postgres's interval
	// range once lockout_count gets large (observed at lockout_count >= 34
	// under concurrent-attempt bursts), which would make this UPDATE error
	// out and turn a login into a 500 instead of the standard 401 envelope —
	// itself a reachable no-oracle break.
	//
	// Both the lockout_count escalation and the locked_until assignment are
	// additionally guarded on "not currently locked"
	// (locked_until IS NULL OR locked_until <= @now): without this guard,
	// concurrent failed attempts that all land after the row is already
	// locked (each serialized in turn by this UPDATE's row lock, but each
	// still satisfying "failed_login_attempts + 1 >= threshold" since the
	// counter only grows) would each re-escalate lockout_count once per
	// attempt rather than once per lockout episode, inflating the doubling
	// exponent far faster than one escalation per actual lockout — which is
	// exactly what fed the interval-overflow bug above.
	//
	// @now is supplied by the caller (the service's injectable clock) rather
	// than Postgres's own now(), so the lockout window is deterministic and
	// testable under a fake clock.
	RecordFailedLoginAttempt(ctx context.Context, arg RecordFailedLoginAttemptParams) (User, error)
	// Clears failed-attempt/lockout-escalation state on a successful login,
	// per RIZ-59's reset semantics ("counter and lockout-escalation reset on
	// successful login after expiry").
	ResetLoginLockout(ctx context.Context, arg ResetLoginLockoutParams) error
	// Scoped by user_id per documentation/security.md §Tenant Isolation.
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) error
	// Scoped by user_id per documentation/security.md §Tenant Isolation: used by
	// logout, where the caller is already authenticated and the family being
	// revoked must belong to them.
	RevokeRefreshTokenFamilyForUser(ctx context.Context, arg RevokeRefreshTokenFamilyForUserParams) error
	// Scoped by user_id per documentation/security.md §Tenant Isolation. Used by
	// DELETE /v1/devices/{id}, which must revoke every refresh token ever issued
	// to that device (not just the currently active family) per
	// documentation/security.md §Token model.
	RevokeRefreshTokensByDevice(ctx context.Context, arg RevokeRefreshTokensByDeviceParams) error
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error)
	// One bounded batch of sync_changelog rows eligible for age-based pruning
	// (RIZ-72): every row whose created_at is strictly before cutoff (the
	// caller-computed now() - SYNC_CHANGELOG_MAX_AGE boundary), oldest
	// (changelog_id) first, capped at batch_limit so a single prune tick never
	// holds a huge result set or a long-running transaction. The caller
	// (internal/sync's retention Pruner) deletes exactly these rows and
	// advances sync_changelog_horizon from their (xid8, server_seq) tuples in
	// the SAME database transaction as this SELECT — see DeleteChangelogRows
	// and AdvanceChangelogHorizon below, and internal/sync/retention.go's
	// PruneOnce for the transactional pairing.
	//
	// xmin_xid8(xmin) (migration 000025) is selected here, before the rows are
	// deleted, because it cannot be recovered afterward — once a row is gone
	// its xmin is gone with it. Capturing it here is what lets the horizon
	// advance to the exact commit-ordered position these rows occupied.
	SelectChangelogPruneBatch(ctx context.Context, arg SelectChangelogPruneBatchParams) ([]SelectChangelogPruneBatchRow, error)
	// DELETE /v1/focus-sessions/{id}. Soft delete via deleted_at so the
	// deletion propagates as a tombstone through GET /v1/sync/changes.
	SoftDeleteFocusSessionForUser(ctx context.Context, arg SoftDeleteFocusSessionForUserParams) (int64, error)
	// DELETE /v1/categories/{id}, restricted to categories the caller owns; a
	// system default cannot be deleted through this query (zero rows if id
	// resolves to one).
	SoftDeleteOwnCategoryForUser(ctx context.Context, arg SoftDeleteOwnCategoryForUserParams) (int64, error)
	// DELETE /v1/projects/{id}. Soft delete via deleted_at per
	// documentation/database-schema.md's "Soft delete via deleted_at"
	// convention, so the deletion propagates to other devices as a tombstone
	// through GET /v1/sync/changes. Scoped by user_id per
	// documentation/security.md §Tenant Isolation; the returned row count lets
	// the caller distinguish "already deleted / not yours / doesn't exist"
	// (0 rows) from a successful delete (1 row), all reported identically as
	// 404 to avoid leaking cross-tenant existence.
	SoftDeleteProjectForUser(ctx context.Context, arg SoftDeleteProjectForUserParams) (int64, error)
	// DELETE /v1/tags/{id}. See projects.sql's SoftDeleteProjectForUser doc
	// comment for the soft-delete/tombstone and 404-equivalence rationale.
	SoftDeleteTagForUser(ctx context.Context, arg SoftDeleteTagForUserParams) (int64, error)
	// server_seq is bumped by the users_set_server_seq BEFORE UPDATE trigger
	// (see migration 000022).
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	// Applies a tombstone push (documentation/sync-protocol.md: "tombstoning
	// an existing event is a subsequent push of the same event_id with
	// deleted: true and the same started_at ... no other field may change on
	// a tombstone push") against a row that already exists under its
	// idempotency key (user_id, event_id, started_at) — i.e. InsertActivityEvent
	// found a conflict and the incoming item is a delete. Only the deleted
	// column is written, preserving the append-only invariant that no other
	// column may be mutated after ingestion. WHERE deleted = false makes a
	// second tombstone push against an already-deleted row a no-op (zero rows
	// returned), which the caller reports as "duplicate" rather than
	// re-"applying" it.
	TombstoneActivityEvent(ctx context.Context, arg TombstoneActivityEventParams) (ActivityEvent, error)
	// Scoped by user_id per documentation/security.md §Tenant Isolation.
	TouchDeviceLastSeen(ctx context.Context, arg TouchDeviceLastSeenParams) error
	// Scoped by user_id per documentation/security.md §Tenant Isolation. Used
	// during login/refresh to refresh a previously-registered device's
	// self-reported metadata and last_seen_at, per documentation/security.md
	// §Token model ("a device row is created/updated and bound to the refresh
	// token").
	UpdateDeviceMetadata(ctx context.Context, arg UpdateDeviceMetadataParams) (Device, error)
	// Scoped by user_id per documentation/security.md §Tenant Isolation. Used by
	// PATCH /v1/devices/{id} ("Rename a device" per documentation/api-reference.md
	// §Devices).
	UpdateDeviceName(ctx context.Context, arg UpdateDeviceNameParams) (Device, error)
	// PATCH /v1/focus-sessions/{id}. See queries/projects.sql's
	// UpdateProjectForUser doc comment for the read-then-merge-then-write
	// pattern and the updated_at rationale (server sets updated_at = now();
	// this is a direct REST edit, not a push-path LWW write).
	UpdateFocusSessionForUser(ctx context.Context, arg UpdateFocusSessionForUserParams) (FocusSession, error)
	// PATCH /v1/categories/{id}, restricted to categories the caller owns (see
	// GetOwnCategoryForUser); a system default cannot be edited through this
	// query (zero rows if id resolves to one).
	UpdateOwnCategoryForUser(ctx context.Context, arg UpdateOwnCategoryForUserParams) (Category, error)
	// Partial update for PATCH /v1/projects/{id}. The service layer reads the
	// current row first and merges caller-supplied fields onto it (matching
	// internal/auth.UpdateProfile's pattern), so every column here is always
	// the final, already-merged value rather than a SQL-side COALESCE.
	// updated_at is always set to the server's now() — direct REST edits are
	// not subject to the client-supplied-updated_at LWW comparison
	// documentation/sync-protocol.md defines for the push path; the
	// server_seq bump (migration 000022's trigger) is what a later sync pull
	// propagates to other devices, and any device that later pushes an older
	// focus_session/project/tag write than this REST edit's new updated_at
	// correctly loses the LWW comparison.
	UpdateProjectForUser(ctx context.Context, arg UpdateProjectForUserParams) (Project, error)
	// PATCH /v1/tags/{id}. See projects.sql's UpdateProjectForUser doc comment
	// for the read-then-merge-then-write pattern and the updated_at rationale.
	UpdateTagForUser(ctx context.Context, arg UpdateTagForUserParams) (Tag, error)
	// server_seq is bumped by the users_set_server_seq BEFORE UPDATE trigger
	// (see migration 000022), which draws from the same server_seq_global
	// sequence used by inserts, per documentation/sync-protocol.md. Callers no
	// longer need to (and must not) set server_seq explicitly on UPDATE — the
	// trigger overwrites whatever value is present.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Last-write-wins upsert for focus_sessions, per
	// documentation/sync-protocol.md §Entity Classes ("Server compares [the
	// client-supplied updated_at] against the currently stored updated_at for
	// that id ... Whichever timestamp wins, the server persists that version
	// and bumps server_seq on the row"). The WHERE clause on the DO UPDATE
	// branch is both the LWW comparison (existing.updated_at < new.updated_at)
	// and a tenant-isolation guard (existing.user_id = new.user_id): if id
	// collides with a row owned by a different user, or the incoming write is
	// not newer, zero rows are returned and the caller distinguishes the two
	// cases via GetFocusSessionByID.
	UpsertFocusSession(ctx context.Context, arg UpsertFocusSessionParams) (FocusSession, error)
}

var _ Querier = (*Queries)(nil)
