// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id, user_id, device_id, token_hash, family_id, issued_at, expires_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, now(), $5
)
RETURNING id, user_id, device_id, token_hash, family_id, issued_at, expires_at, revoked_at, replaced_by
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	TokenHash []byte             `json:"token_hash"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.DeviceID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.FamilyID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, device_id, token_hash, family_id, issued_at, expires_at, revoked_at, replaced_by FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.FamilyID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT id, user_id, device_id, token_hash, family_id, issued_at, expires_at, revoked_at, replaced_by FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

// Blocking row lock, used only after GetRefreshTokenByHashForUpdateNoWait
// has detected contention: waits for the concurrently in-flight rotation to
// commit, then returns the now-serialized, final row state (RIZ-32 M2).
func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.FamilyID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getRefreshTokenByHashForUpdateNoWait = `-- name: GetRefreshTokenByHashForUpdateNoWait :one
SELECT id, user_id, device_id, token_hash, family_id, issued_at, expires_at, revoked_at, replaced_by FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE NOWAIT
`

// Locks the refresh token row without blocking (SQLSTATE 55P03
// lock_not_available if another transaction already holds the lock), so the
// caller can distinguish "I am racing a concurrently in-flight rotation of
// this exact token" from "I am the only one looking at this row right now",
// per documentation/security.md's refresh-rotation flow (RIZ-32 M2).
func (q *Queries) GetRefreshTokenByHashForUpdateNoWait(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdateNoWait, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.FamilyID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const listActiveRefreshTokensByUser = `-- name: ListActiveRefreshTokensByUser :many
SELECT id, user_id, device_id, token_hash, family_id, issued_at, expires_at, revoked_at, replaced_by FROM refresh_tokens
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY issued_at DESC
`

func (q *Queries) ListActiveRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveRefreshTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.TokenHash,
			&i.FamilyID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ReplacedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}

const revokeRefreshTokenFamilyForUser = `-- name: RevokeRefreshTokenFamilyForUser :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyForUserParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Scoped by user_id per documentation/security.md §Tenant Isolation: used by
// logout, where the caller is already authenticated and the family being
// revoked must belong to them.
func (q *Queries) RevokeRefreshTokenFamilyForUser(ctx context.Context, arg RevokeRefreshTokenFamilyForUserParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamilyForUser, arg.FamilyID, arg.UserID)
	return err
}

const revokeRefreshTokensByDevice = `-- name: RevokeRefreshTokensByDevice :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE device_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokensByDeviceParams struct {
	DeviceID pgtype.UUID `json:"device_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Scoped by user_id per documentation/security.md §Tenant Isolation. Used by
// DELETE /v1/devices/{id}, which must revoke every refresh token ever issued
// to that device (not just the currently active family) per
// documentation/security.md §Token model.
func (q *Queries) RevokeRefreshTokensByDevice(ctx context.Context, arg RevokeRefreshTokensByDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByDevice, arg.DeviceID, arg.UserID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = now(),
    replaced_by = $2
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, device_id, token_hash, family_id, issued_at, expires_at, revoked_at, replaced_by
`

type RotateRefreshTokenParams struct {
	ID         pgtype.UUID `json:"id"`
	ReplacedBy pgtype.UUID `json:"replaced_by"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.ID, arg.ReplacedBy)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.FamilyID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}
