// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_retention.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceChangelogHorizon = `-- name: AdvanceChangelogHorizon :one
UPDATE sync_changelog_horizon
SET horizon_xid8       = GREATEST(horizon_xid8, $1::xid8),
    horizon_server_seq  = GREATEST(horizon_server_seq, $2::bigint),
    pruned_at           = now(),
    updated_at          = now()
WHERE id
RETURNING horizon_xid8, horizon_server_seq
`

type AdvanceChangelogHorizonParams struct {
	Xid8      pgtype.Uint64 `json:"xid8"`
	ServerSeq int64         `json:"server_seq"`
}

type AdvanceChangelogHorizonRow struct {
	HorizonXid8      pgtype.Uint64 `json:"horizon_xid8"`
	HorizonServerSeq int64         `json:"horizon_server_seq"`
}

// Advances the single sync_changelog_horizon row to the maximum of its
// current (horizon_xid8, horizon_server_seq) and the caller-supplied
// values (the max xid8/server_seq among the batch just deleted). GREATEST
// (rather than an unconditional SET) makes this safe to call with a batch
// whose max happens to be behind the already-recorded horizon — which
// cannot happen in the normal single-pruner-instance case (batches are
// processed in changelog_id order, which is also non-decreasing in
// (xid8, server_seq) per migration 000025's gap-free-by-construction
// invariant) but keeps this query correct/idempotent under retry or a
// hypothetical second pruner instance rather than relying on that
// invariant to hold at the call site too.
func (q *Queries) AdvanceChangelogHorizon(ctx context.Context, arg AdvanceChangelogHorizonParams) (AdvanceChangelogHorizonRow, error) {
	row := q.db.QueryRow(ctx, advanceChangelogHorizon, arg.Xid8, arg.ServerSeq)
	var i AdvanceChangelogHorizonRow
	err := row.Scan(&i.HorizonXid8, &i.HorizonServerSeq)
	return i, err
}

const deleteChangelogRows = `-- name: DeleteChangelogRows :execrows
DELETE FROM sync_changelog
WHERE changelog_id = ANY($1::bigint[])
`

// Deletes exactly the rows SelectChangelogPruneBatch identified, by their
// changelog_id primary keys, in the SAME transaction as that select. Using
// the exact id set (rather than re-evaluating the created_at < cutoff
// predicate a second time) means this DELETE can never race with a
// concurrent write that inserted a new, unrelated row after the select ran
// but before the delete executes — it only ever touches the exact rows
// already identified as prune candidates.
func (q *Queries) DeleteChangelogRows(ctx context.Context, changelogIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChangelogRows, changelogIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChangelogHorizon = `-- name: GetChangelogHorizon :one
SELECT horizon_xid8, horizon_server_seq FROM sync_changelog_horizon WHERE id
`

type GetChangelogHorizonRow struct {
	HorizonXid8      pgtype.Uint64 `json:"horizon_xid8"`
	HorizonServerSeq int64         `json:"horizon_server_seq"`
}

// Reads the current retained horizon, per internal/sync/pull.go's
// cursor-reset check: a pull whose caller-supplied cursor is strictly
// below this position cannot be served a gap-free page (rows between its
// cursor and here were deleted by age-based retention) and must be told to
// reset instead. Called inside the same REPEATABLE READ, READ ONLY
// transaction as the rest of a pull (runInPullSnapshot) so the horizon
// check and the changelog page read observe one consistent snapshot.
func (q *Queries) GetChangelogHorizon(ctx context.Context) (GetChangelogHorizonRow, error) {
	row := q.db.QueryRow(ctx, getChangelogHorizon)
	var i GetChangelogHorizonRow
	err := row.Scan(&i.HorizonXid8, &i.HorizonServerSeq)
	return i, err
}

const selectChangelogPruneBatch = `-- name: SelectChangelogPruneBatch :many
SELECT changelog_id, xmin_xid8(xmin) AS xid8, server_seq
FROM sync_changelog
WHERE created_at < $1::timestamptz
ORDER BY changelog_id
LIMIT $2
`

type SelectChangelogPruneBatchParams struct {
	Cutoff     pgtype.Timestamptz `json:"cutoff"`
	BatchLimit int32              `json:"batch_limit"`
}

type SelectChangelogPruneBatchRow struct {
	ChangelogID int64         `json:"changelog_id"`
	Xid8        pgtype.Uint64 `json:"xid8"`
	ServerSeq   int64         `json:"server_seq"`
}

// One bounded batch of sync_changelog rows eligible for age-based pruning
// (RIZ-72): every row whose created_at is strictly before cutoff (the
// caller-computed now() - SYNC_CHANGELOG_MAX_AGE boundary), oldest
// (changelog_id) first, capped at batch_limit so a single prune tick never
// holds a huge result set or a long-running transaction. The caller
// (internal/sync's retention Pruner) deletes exactly these rows and
// advances sync_changelog_horizon from their (xid8, server_seq) tuples in
// the SAME database transaction as this SELECT — see DeleteChangelogRows
// and AdvanceChangelogHorizon below, and internal/sync/retention.go's
// PruneOnce for the transactional pairing.
//
// xmin_xid8(xmin) (migration 000025) is selected here, before the rows are
// deleted, because it cannot be recovered afterward — once a row is gone
// its xmin is gone with it. Capturing it here is what lets the horizon
// advance to the exact commit-ordered position these rows occupied.
func (q *Queries) SelectChangelogPruneBatch(ctx context.Context, arg SelectChangelogPruneBatchParams) ([]SelectChangelogPruneBatchRow, error) {
	rows, err := q.db.Query(ctx, selectChangelogPruneBatch, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectChangelogPruneBatchRow
	for rows.Next() {
		var i SelectChangelogPruneBatchRow
		if err := rows.Scan(&i.ChangelogID, &i.Xid8, &i.ServerSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
