// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (
    id, bundle_id, platform, name
) VALUES (
    gen_random_uuid(), $1, $2, $3
)
ON CONFLICT (bundle_id, platform) DO NOTHING
RETURNING id, bundle_id, platform, name, default_category_id
`

type CreateAppParams struct {
	BundleID string `json:"bundle_id"`
	Platform string `json:"platform"`
	Name     string `json:"name"`
}

// Auto-creates an apps row the first time a bundle_id/platform pair is
// observed during ingestion, per documentation/architecture-backend.md
// §Ingestion Pipeline ("if no matching row exists, one is created
// automatically"). ON CONFLICT DO NOTHING (rather than erroring) makes this
// safe to call optimistically under a race with a concurrent ingestion of
// the same new bundle_id/platform; a caller that gets zero rows back must
// re-fetch via GetAppByBundleID.
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp, arg.BundleID, arg.Platform, arg.Name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.Platform,
		&i.Name,
		&i.DefaultCategoryID,
	)
	return i, err
}

const getAppByBundleID = `-- name: GetAppByBundleID :one
SELECT id, bundle_id, platform, name, default_category_id FROM apps
WHERE bundle_id = $1 AND platform = $2
`

type GetAppByBundleIDParams struct {
	BundleID string `json:"bundle_id"`
	Platform string `json:"platform"`
}

// Looks up the global app-catalog row for a (bundle_id, platform) pair, per
// documentation/database-schema.md's `UNIQUE (bundle_id, platform)` on
// `apps`. Not user-scoped: the catalog is global/cross-user by design (see
// documentation/architecture-backend.md §Ingestion Pipeline, stage 2).
func (q *Queries) GetAppByBundleID(ctx context.Context, arg GetAppByBundleIDParams) (App, error) {
	row := q.db.QueryRow(ctx, getAppByBundleID, arg.BundleID, arg.Platform)
	var i App
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.Platform,
		&i.Name,
		&i.DefaultCategoryID,
	)
	return i, err
}

const getFocusSessionByID = `-- name: GetFocusSessionByID :one
SELECT id, user_id, device_id, project_id, kind, planned_duration_s, started_at, ended_at, status, note, created_at, updated_at, deleted_at, server_seq FROM focus_sessions
WHERE id = $1
`

// Unscoped-by-user lookup used only to distinguish, after an
// UpsertFocusSession call returns zero rows, whether the existing row
// under this id belongs to a different user entirely (a tenant-isolation
// violation, reported as "invalid") from a same-user last-write-wins loss
// (reported as "duplicate") — see internal/sync's push service.
func (q *Queries) GetFocusSessionByID(ctx context.Context, id pgtype.UUID) (FocusSession, error) {
	row := q.db.QueryRow(ctx, getFocusSessionByID, id)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ProjectID,
		&i.Kind,
		&i.PlannedDurationS,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getUserAppSettingByUserAndApp = `-- name: GetUserAppSettingByUserAndApp :one
SELECT user_id, app_id, category_id, excluded, updated_at, server_seq FROM user_app_settings
WHERE user_id = $1 AND app_id = $2
`

type GetUserAppSettingByUserAndAppParams struct {
	UserID pgtype.UUID `json:"user_id"`
	AppID  pgtype.UUID `json:"app_id"`
}

// The user-specific override consulted by category resolution's first
// fallback step, per documentation/architecture-backend.md §Ingestion
// Pipeline stage 3. Scoped by user_id per documentation/security.md
// §Tenant Isolation.
func (q *Queries) GetUserAppSettingByUserAndApp(ctx context.Context, arg GetUserAppSettingByUserAndAppParams) (UserAppSetting, error) {
	row := q.db.QueryRow(ctx, getUserAppSettingByUserAndApp, arg.UserID, arg.AppID)
	var i UserAppSetting
	err := row.Scan(
		&i.UserID,
		&i.AppID,
		&i.CategoryID,
		&i.Excluded,
		&i.UpdatedAt,
		&i.ServerSeq,
	)
	return i, err
}

const insertActivityEvent = `-- name: InsertActivityEvent :one
INSERT INTO activity_events (
    event_id, user_id, device_id, started_at, ended_at,
    type, source, precision,
    app_id, raw_bundle_id, window_title, url,
    category_id, project_id, deleted, inserted_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, now()
)
ON CONFLICT ON CONSTRAINT activity_events_idempotency_key DO NOTHING
RETURNING event_id, user_id, device_id, started_at, ended_at, duration_s, type, source, precision, app_id, raw_bundle_id, window_title, url, category_id, project_id, deleted, inserted_at, server_seq
`

type InsertActivityEventParams struct {
	EventID     pgtype.UUID        `json:"event_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	DeviceID    pgtype.UUID        `json:"device_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	Type        string             `json:"type"`
	Source      string             `json:"source"`
	Precision   string             `json:"precision"`
	AppID       pgtype.UUID        `json:"app_id"`
	RawBundleID *string            `json:"raw_bundle_id"`
	WindowTitle *string            `json:"window_title"`
	Url         *string            `json:"url"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Deleted     bool               `json:"deleted"`
}

// Idempotent insert for the append-only activity_events hypertable, per
// documentation/sync-protocol.md §Entity Classes ("Idempotency key is the
// composite UNIQUE (user_id, event_id, started_at) constraint"). ON
// CONFLICT DO NOTHING means a retried/replayed push of the same event
// returns zero rows, which the caller reports as a "duplicate" per-item
// result rather than an error. Scoped by user_id (the row is created for
// the authenticated caller only, never for a user_id supplied by the
// request body) per documentation/security.md §Tenant Isolation.
func (q *Queries) InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, insertActivityEvent,
		arg.EventID,
		arg.UserID,
		arg.DeviceID,
		arg.StartedAt,
		arg.EndedAt,
		arg.Type,
		arg.Source,
		arg.Precision,
		arg.AppID,
		arg.RawBundleID,
		arg.WindowTitle,
		arg.Url,
		arg.CategoryID,
		arg.ProjectID,
		arg.Deleted,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.DeviceID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationS,
		&i.Type,
		&i.Source,
		&i.Precision,
		&i.AppID,
		&i.RawBundleID,
		&i.WindowTitle,
		&i.Url,
		&i.CategoryID,
		&i.ProjectID,
		&i.Deleted,
		&i.InsertedAt,
		&i.ServerSeq,
	)
	return i, err
}

const tombstoneActivityEvent = `-- name: TombstoneActivityEvent :one
UPDATE activity_events
SET deleted = true
WHERE user_id = $1 AND event_id = $2 AND started_at = $3 AND deleted = false
RETURNING event_id, user_id, device_id, started_at, ended_at, duration_s, type, source, precision, app_id, raw_bundle_id, window_title, url, category_id, project_id, deleted, inserted_at, server_seq
`

type TombstoneActivityEventParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	EventID   pgtype.UUID        `json:"event_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

// Applies a tombstone push (documentation/sync-protocol.md: "tombstoning
// an existing event is a subsequent push of the same event_id with
// deleted: true and the same started_at ... no other field may change on
// a tombstone push") against a row that already exists under its
// idempotency key (user_id, event_id, started_at) — i.e. InsertActivityEvent
// found a conflict and the incoming item is a delete. Only the deleted
// column is written, preserving the append-only invariant that no other
// column may be mutated after ingestion. WHERE deleted = false makes a
// second tombstone push against an already-deleted row a no-op (zero rows
// returned), which the caller reports as "duplicate" rather than
// re-"applying" it.
func (q *Queries) TombstoneActivityEvent(ctx context.Context, arg TombstoneActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, tombstoneActivityEvent, arg.UserID, arg.EventID, arg.StartedAt)
	var i ActivityEvent
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.DeviceID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationS,
		&i.Type,
		&i.Source,
		&i.Precision,
		&i.AppID,
		&i.RawBundleID,
		&i.WindowTitle,
		&i.Url,
		&i.CategoryID,
		&i.ProjectID,
		&i.Deleted,
		&i.InsertedAt,
		&i.ServerSeq,
	)
	return i, err
}

const upsertFocusSession = `-- name: UpsertFocusSession :one
INSERT INTO focus_sessions (
    id, user_id, device_id, project_id, kind, planned_duration_s,
    started_at, ended_at, status, note, created_at, updated_at, deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, now(), $11, $12
)
ON CONFLICT (id) DO UPDATE SET
    device_id          = EXCLUDED.device_id,
    project_id         = EXCLUDED.project_id,
    kind               = EXCLUDED.kind,
    planned_duration_s = EXCLUDED.planned_duration_s,
    started_at         = EXCLUDED.started_at,
    ended_at           = EXCLUDED.ended_at,
    status             = EXCLUDED.status,
    note               = EXCLUDED.note,
    updated_at         = EXCLUDED.updated_at,
    deleted_at         = EXCLUDED.deleted_at
WHERE focus_sessions.user_id = EXCLUDED.user_id
  AND focus_sessions.updated_at < EXCLUDED.updated_at
RETURNING id, user_id, device_id, project_id, kind, planned_duration_s, started_at, ended_at, status, note, created_at, updated_at, deleted_at, server_seq
`

type UpsertFocusSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Kind             string             `json:"kind"`
	PlannedDurationS *int32             `json:"planned_duration_s"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	Status           string             `json:"status"`
	Note             *string            `json:"note"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

// Last-write-wins upsert for focus_sessions, per
// documentation/sync-protocol.md §Entity Classes ("Server compares [the
// client-supplied updated_at] against the currently stored updated_at for
// that id ... Whichever timestamp wins, the server persists that version
// and bumps server_seq on the row"). The WHERE clause on the DO UPDATE
// branch is both the LWW comparison (existing.updated_at < new.updated_at)
// and a tenant-isolation guard (existing.user_id = new.user_id): if id
// collides with a row owned by a different user, or the incoming write is
// not newer, zero rows are returned and the caller distinguishes the two
// cases via GetFocusSessionByID.
func (q *Queries) UpsertFocusSession(ctx context.Context, arg UpsertFocusSessionParams) (FocusSession, error) {
	row := q.db.QueryRow(ctx, upsertFocusSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.ProjectID,
		arg.Kind,
		arg.PlannedDurationS,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status,
		arg.Note,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i FocusSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.ProjectID,
		&i.Kind,
		&i.PlannedDurationS,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}
