// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTagForUser = `-- name: CreateTagForUser :one
INSERT INTO tags (
    id, user_id, name, updated_at
) VALUES (
    $1, $2, $3, now()
)
RETURNING id, user_id, name, updated_at, deleted_at, server_seq
`

type CreateTagForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

// Creates a tag owned by the authenticated user, per
// documentation/api-reference.md §CRUD groups ("POST /v1/tags"). A
// concurrent/duplicate name for the same user surfaces as a unique
// violation on tags' UNIQUE (user_id, name) constraint, mapped by the
// caller via store.ConstraintViolation to a 409 Conflict.
func (q *Queries) CreateTagForUser(ctx context.Context, arg CreateTagForUserParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTagForUser, arg.ID, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getTagForUser = `-- name: GetTagForUser :one
SELECT id, user_id, name, updated_at, deleted_at, server_seq FROM tags
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTagForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Tenant-scoped lookup for GET /v1/tags/{id}. Zero rows for either "no
// such tag" or "belongs to another user," per
// documentation/security.md §Tenant Isolation, so the two cases are
// reported identically as 404.
func (q *Queries) GetTagForUser(ctx context.Context, arg GetTagForUserParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagForUser, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const listTagsForUser = `-- name: ListTagsForUser :many
SELECT id, user_id, name, updated_at, deleted_at, server_seq FROM tags
WHERE user_id = $1 AND deleted_at IS NULL AND server_seq > $2
ORDER BY server_seq ASC
LIMIT $3
`

type ListTagsForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ServerSeq int64       `json:"server_seq"`
	Limit     int32       `json:"limit"`
}

// Keyset-paginated list for GET /v1/tags, per
// documentation/api-reference.md §Conventions. Scoped by user_id per
// documentation/security.md §Tenant Isolation; excludes soft-deleted rows.
func (q *Queries) ListTagsForUser(ctx context.Context, arg ListTagsForUserParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForUser, arg.UserID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ServerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTagForUser = `-- name: SoftDeleteTagForUser :execrows
UPDATE tags
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTagForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// DELETE /v1/tags/{id}. See projects.sql's SoftDeleteProjectForUser doc
// comment for the soft-delete/tombstone and 404-equivalence rationale.
func (q *Queries) SoftDeleteTagForUser(ctx context.Context, arg SoftDeleteTagForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTagForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTagForUser = `-- name: UpdateTagForUser :one
UPDATE tags
SET name = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, updated_at, deleted_at, server_seq
`

type UpdateTagForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

// PATCH /v1/tags/{id}. See projects.sql's UpdateProjectForUser doc comment
// for the read-then-merge-then-write pattern and the updated_at rationale.
func (q *Queries) UpdateTagForUser(ctx context.Context, arg UpdateTagForUserParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTagForUser, arg.ID, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}
