// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, password_hash, apple_user_id, display_name, role, timezone,
    created_at, updated_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6,
    now(), now()
)
RETURNING id, email, password_hash, apple_user_id, display_name, role, timezone, created_at, updated_at, deleted_at, server_seq
`

type CreateUserParams struct {
	Email        *string `json:"email"`
	PasswordHash *string `json:"password_hash"`
	AppleUserID  *string `json:"apple_user_id"`
	DisplayName  *string `json:"display_name"`
	Role         string  `json:"role"`
	Timezone     *string `json:"timezone"`
}

// Callers pass the desired role explicitly ('user' by default); the
// database-side DEFAULT 'user' on this column only applies when the column
// is omitted from an INSERT's column list, which sqlc's generated,
// fully-columned INSERT never does.
//
// server_seq is intentionally omitted from the column list: the
// users_set_server_seq BEFORE INSERT trigger (see migration 000022)
// unconditionally assigns it from the shared server_seq_global sequence,
// keeping every syncable table's server_seq drawn from the same global
// sequence space per documentation/sync-protocol.md.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.AppleUserID,
		arg.DisplayName,
		arg.Role,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.DisplayName,
		&i.Role,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getUserByAppleUserID = `-- name: GetUserByAppleUserID :one
SELECT id, email, password_hash, apple_user_id, display_name, role, timezone, created_at, updated_at, deleted_at, server_seq FROM users
WHERE apple_user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByAppleUserID(ctx context.Context, appleUserID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAppleUserID, appleUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.DisplayName,
		&i.Role,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, apple_user_id, display_name, role, timezone, created_at, updated_at, deleted_at, server_seq FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.DisplayName,
		&i.Role,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, apple_user_id, display_name, role, timezone, created_at, updated_at, deleted_at, server_seq FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.DisplayName,
		&i.Role,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// server_seq is bumped by the users_set_server_seq BEFORE UPDATE trigger
// (see migration 000022).
func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2,
    timezone = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, apple_user_id, display_name, role, timezone, created_at, updated_at, deleted_at, server_seq
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName *string     `json:"display_name"`
	Timezone    *string     `json:"timezone"`
}

// server_seq is bumped by the users_set_server_seq BEFORE UPDATE trigger
// (see migration 000022), which draws from the same server_seq_global
// sequence used by inserts, per documentation/sync-protocol.md. Callers no
// longer need to (and must not) set server_seq explicitly on UPDATE — the
// trigger overwrites whatever value is present.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleUserID,
		&i.DisplayName,
		&i.Role,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ServerSeq,
	)
	return i, err
}
